services:
  - type: web
    name: django-portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn WhoAmI.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: your-subdomain.onrender.com