# Generated by Django 6.0 on 2025-12-16 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('development', 'Development'), ('designing', 'Designing'), ('video-editing', 'Video Editing')], max_length=50)),
                ('tech_stack', models.JSONField(default=list)),
                ('thumbnail', models.ImageField(upload_to='projects/')),
                ('project_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('type', models.CharField(choices=[('local', 'Local Video'), ('instagram', 'Instagram Reel')], default='local', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.project')),
            ],
        ),
    ]
