# Generated by Django 6.0 on 2025-12-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('development', 'Development'), ('video-editing', 'Video Editing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='URL to GitHub repository', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='URL to live website', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(default=list, help_text='Enter as JSON array: ["Django", "Tailwind CSS"]'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_file',
            field=models.FileField(blank=True, help_text='Preview video for project detail page', null=True, upload_to='videos/'),
        ),
    ]
